export const

	users = [{
		uuid: '1e8b6bf0-1b50-11ec-85ec-4d033c80c035',
		username: 'TeazYou',
		// password below is '23455678' generated by:
		// -> npm run script ./scripts/hashPassword.script.js 23455678
		password: '$2b$12$IqO3mVn6Nte7vBiwCb2Ye.YLZju9.Gq8plSUsEjLen9FU6su7bjja',
	}]
